### ISSUE TITLE
How can I use this library with nativescript

### ISSUE THREAD

**Issue by jcamino1972** [faisalsami/odoo-xmlrpc#11]
Hello,

Please, clould you tell me if is it possible to use this library with nativescript to build android app.

Thank you for your help.

Jorge

**Comment by faisalsami** [comment]
Hi, You can try xmlrpc library for php and call into that from your nativescript or you can implement a http server and use odoo-xmlrpc library into that.

**Comment by jcamino1972** [comment]
Hi, Thank you for your help.
