### ISSUE TITLE
please remove unnecessary console.log's

### ISSUE THREAD

**Issue by novardanak** [faisalsami/odoo-xmlrpc#13]
in index.js, if it is secure connection, some unnecessary console.log's appearing:

index.js line 40-41
40: console.log(clientOptions)
41: console.log("client sécurisé sur le port " + this.port)

could you please remove it. Thank you.

**Comment by fnaquira** [comment]
I am here to write the same petition

**Comment by faisalsami** [comment]
updated on npm.
