### ISSUE TITLE
async/await version of the API

### ISSUE THREAD

**Issue by ajit-kumar-azad** [faisalsami/odoo-xmlrpc#14]
Hi There!

Thanks a tonne for the library. It has been working very well so far. Wanted to check with you if there is an async/await version of the API that you have on your roadmap!

**Comment by dennybiasiolli** [comment]
I can provide a PR in  a few days 😉

**Comment by lekhnath** [comment]
When will this feature become available?

**Comment by dennybiasiolli** [comment]
We have to ask the maintainer @faisalsami , I can help with the coding part

**Comment by Amin-Cheribet** [comment]
is this library still maintained  ?

**Comment by dennybiasiolli** [comment]
@Amin-Cheribet nice question, @faisalsami please answer us

**Comment by ansmlc** [comment]
Hi, any news on this?
@Amin-Cheribet @dennybiasiolli @lekhnath 
Sorry to spam but have found any solution? Is there an alternative library that's maintained?

**Comment by dennybiasiolli** [comment]
I think this library is abandoned, no news from @faisalsami and I don't have permissions to merge pull requests, sorry

**Comment by Amin-Cheribet** [comment]
@ansmlc yes i have adapted the code to async/await,
Unfortunately i can't share the code here since it was developed for a private company.
