### ISSUE TITLE
xmlrpc/2/common 404

### ISSUE THREAD

**Issue by afandylamusu** [faisalsami/odoo-xmlrpc#4]
Hi,

I'm using odoo v-10 open source.
Could you please help me about response 404 on authentication method?

Thanks 

![image](https://cloud.githubusercontent.com/assets/6712144/23121501/3a86297a-f793-11e6-9efc-ae8ffed6b03a.png)

**Comment by rossigee** [comment]
This will be related to your web server's CORS configuration, or your web proxy configuration not passing CORS-related headers. This does not appear to be a bug in odoo-xmlrpc.
